apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
      - name: ganache
        image: yuval.dev/ganache-cli
        args:
          - --deterministic
          - --host
          - "0.0.0.0"
        imagePullPolicy: Never
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8545
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
spec:
  type: NodePort
  selector:
    app: ganache
  ports:
  - port: 8545
    targetPort: 8545
    nodePort: 32000
